-- 코드를 작성해주세요
SELECT E1.ID
FROM ECOLI_DATA E1
LEFT JOIN ECOLI_DATA E2 ON E1.PARENT_ID = E2.ID
LEFT JOIN ECOLI_DATA E3 ON E2.PARENT_ID = E3.ID
WHERE E3.ID IS NOT NULL AND E3.PARENT_ID IS NULL
ORDER BY 1