SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30) * (1-P.DISCOUNT_RATE/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
AND C.CAR_TYPE IN ('세단', 'SUV')
AND P.DURATION_TYPE LIKE '30%'
HAVING FEE >= 500000 AND FEE<2000000
ORDER BY 3 DESC, 2, 1 DESC