SELECT E1.ID, CASE WHEN E2.GRADE <= 0.25 THEN 'CRITICAL'
                    WHEN E2.GRADE <= 0.5 THEN 'HIGH'
                    WHEN E2.GRADE <= 0.75 THEN 'MEDIUM'
                    ELSE 'LOW'
                END AS COLONY_NAME
FROM ECOLI_DATA E1
NATURAL JOIN (SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(*) FROM ECOLI_DATA) AS GRADE
FROM ECOLI_DATA) E2
ORDER BY 1