SELECT YEAR(S.SALES_DATE) YEAR,MONTH(S.SALES_DATE) MONTH, COUNT(DISTINCT S.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'),1) PCHASED_RATIO
FROM USER_INFO I JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE JOINED LIKE '2021%'
GROUP BY YEAR(S.SALES_DATE),MONTH(S.SALES_DATE)
ORDER BY 1,2