WITH RECURSIVE ECOLI_DATA_GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D.ID, D.PARENT_ID, G.GENERATION+1
    FROM ECOLI_DATA D
    JOIN ECOLI_DATA_GENERATION G ON D.PARENT_ID = G.ID
),
ECOLI_DATA_GENERATION2 AS (
    SELECT ID,PARENT_ID, GENERATION, (SELECT COUNT(*)
                                      FROM ECOLI_DATA_GENERATION D
                                      WHERE G.ID = D.PARENT_ID
                                     ) CHILD_COUNT
    FROM ECOLI_DATA_GENERATION G
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_DATA_GENERATION2
WHERE CHILD_COUNT = 0
GROUP BY GENERATION
ORDER BY 2