SELECT FLAVOR
FROM FIRST_HALF A
NATURAL JOIN (
                SELECT FLAVOR, SUM(TOTAL_ORDER) T
                FROM JULY
                GROUP BY FLAVOR
             ) AS B
ORDER BY (A.TOTAL_ORDER + B.T) DESC
LIMIT 3