-- 코드를 입력하세요
WITH RECURSIVE A AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1
    FROM A
    WHERE NUM<23
)
SELECT A.NUM, IFNULL(B.COUNT,0)
FROM A 
LEFT JOIN (SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
            FROM ANIMAL_OUTS
            GROUP BY HOUR(DATETIME)) AS B
ON A.NUM = B.HOUR
ORDER BY 1