WITH RECURSIVE HOURS AS(
    SELECT 0 HOUR
    
    UNION ALL
    
    SELECT HOUR+1
    FROM HOURS
    WHERE HOUR<23
)
SELECT HOURS.HOUR, COALESCE(CNT.COUNT, 0)
FROM HOURS
LEFT JOIN (SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
            FROM ANIMAL_OUTS
            GROUP BY HOUR(DATETIME)) CNT
ON HOURS.HOUR = CNT.HOUR
ORDER BY 1