-- 코드를 입력하세요
SELECT CONCAT_WS('/', '/home/grep/src', B.BOARD_ID,CONCAT(FILE_ID,FILE_NAME,FILE_EXT)) FILE_PATH
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_FILE F
ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC